server:
  port: 9003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.17:3306/zyg_manager?serverTimezone=UTC
    username: root
    password: 123
  thymeleaf:
    cache: false

  redis:
    host: 192.168.56.17
  application:
    name: zyg-search

logging:
  level:
    com.zyg.search: debug

elasticsearch:
  host: 192.168.56.17
  port: 9200
