server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.17:3306/zyg_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezon=Asia/Shanghai
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com.zey: debug
