#server:
#  port: 9001
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.17:3307/zyg_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123
#
#  thymeleaf:
#    cache: false
##    prefix: classpath:/templates/       默认就这俩  所以不用配置
##    suffix: .html
#
#
#  redis:
#    host: 192.168.56.17
#    port: 6379

#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#
#  application:
#    name: zyg-manager
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#
#
#
#logging:
#  level:
#    com.zyg: debug