server:
  port: 9007

spring:
  application:
    name: zyg-order

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.17:3306/zyg_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.17
logging:
  level:
    com.zyg: debug
