server:
  port: 9006

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.17:3306/zyg_cart?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123

  application:
    name: zyg-cart

  thymeleaf:
    cache: false

  redis:
    host: 192.168.56.17



logging:
  level:
    com.cart: debug